# Generated by Django 4.0.4 on 2022-08-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_skill_delete_element'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='socail_page',
            new_name='social_page',
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
