# Generated by Django 4.0.4 on 2022-08-23 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_inboxmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['created']},
        ),
        migrations.RenameField(
            model_name='inboxmessage',
            old_name='recipent',
            new_name='recipient',
        ),
    ]
