# Generated by Django 4.0.4 on 2022-08-01 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hacker', '0004_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='rooms',
            new_name='room',
        ),
    ]
