# Generated by Django 4.0.4 on 2022-08-07 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hacker', '0011_pizza_topping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '  Tags',
            },
        ),
        migrations.RenameModel(
            old_name='Pizza',
            new_name='contacts',
        ),
        migrations.RenameModel(
            old_name='Topping',
            new_name='Projects',
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name_plural': '   Message'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name_plural': ' Projects'},
        ),
        migrations.RemoveField(
            model_name='message',
            name='body',
        ),
        migrations.RemoveField(
            model_name='message',
            name='created',
        ),
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
