# Generated by Django 4.0.4 on 2022-08-17 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hacker', '0013_delete_contacts_delete_projects_delete_tags_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created']},
        ),
    ]
