# Generated by Django 4.0.4 on 2022-08-17 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hacker', '0015_review_owner_alter_review_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
