# Generated by Django 4.0.4 on 2022-08-22 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hacker', '0017_alter_project_options_inboxmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InboxMessage',
        ),
    ]
