# Generated by Django 4.0.4 on 2022-09-06 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hacker', '0020_message_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
    ]
