# Generated by Django 4.0.4 on 2022-10-05 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hacker', '0022_fitnessplan_alter_message_options_alter_message_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('content', models.TextField()),
                ('slug', models.SlugField(max_length=255)),
            ],
        ),
    ]
