# Generated by Django 4.0.4 on 2022-10-05 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hacker', '0023_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Blog',
        ),
    ]
