# Generated by Django 4.0.4 on 2022-10-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hacker', '0024_rename_post_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
